baseurl      = "/"
title        = "My Site"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Hi! My name is Rachel and I'm a current MS Cybersecurity student at NYU Tandon."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/RachelTaoRuiqi"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rachel-ruiqi-tao-26007a16a/"

  [[params.social]]
    name = "tryhackme"
    url = "https://tryhackme.com/p/RuaRua"

  [[params.social]]
    name = "github"
    url = "https://github.com/Racheltrq"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "About Me"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /Welcome/Racheltao"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/"

  [[menu.main]]
    identifier = "Notes"
    name       = "Notes"
    url        = "/notes"

#  [[menu.main]]
#    identifier = "project"
#    name       = "Project"
#    url        = "/projects"

  


